### ISSUE TITLE
RFE: Add and support detox

### ISSUE THREAD

**Issue by hroncok** [frenzymadness/fedora-python-tox#19]
Detox (fedora package python-detox, or python3-detox when built) allow to run tox environments in parallel. Would you accept a PR that adds it?

**Comment by hroncok** [comment]
and eventlet.

**Comment by frenzymadness** [comment]
Ok, let's add it and we'll see.

Is it automatically activated for every tox run so it will speed up users testing? I am asking because in Travis we are using the separated build for each environment so it won't have any impact.

**Comment by hroncok** [comment]
No. User needs to use the `detox` command to benefit form it.

**Comment by frenzymadness** [comment]
Let's try it.

**Comment by hroncok** [comment]
on it.
