### ISSUE TITLE
[RFE] Auto-clone project

### ISSUE THREAD

**Issue by fivaldi** [frenzymadness/fedora-python-tox#8]
It would be nice to pass _somehow_ git URL into the docker so that it would automatically clone the requested repository and run tox command on top of it using the supplied `tox.ini` from `fedora-python-tox`.

It could be done using env. variables, extending docker entry point with additional/custom arguments taken from `docker run`, some special config file (with multiple git URLs) etc.

**Comment by frenzymadness** [comment]
I know what you mean but could you please mention some use case for this?

In all my use cases, I prefer to have project source code in some folder outside of the container and use Docker just for testing.

**Comment by fivaldi** [comment]
I mean automated testing.

The git URL could be "file:///" which would cover your scenario as well.

**Comment by frenzymadness** [comment]
I probably understand you. You want to use this Docker container for automated tests, so you want to clone project and run tox tests in one command so then you can run it without manual cloning project.

So when some environment variable with project URL will be defined, clone this project to current working directory before text execution. Am I right?

**Comment by fivaldi** [comment]
YES!!! Absolutely!!!

**Comment by frenzymadness** [comment]
Implemented in the linked pull request.
