### ISSUE TITLE
Consider to rewrite tests in example project to unittest

### ISSUE THREAD

**Issue by frenzymadness** [frenzymadness/fedora-python-tox#9]
Because there seem to be some incompatibilities between attrs module (pytest dependency) and Jython, it might make sense to rewrite tests to use the unittest module instead of pytest.

https://github.com/pytest-dev/pytest/issues/3111
https://github.com/python-attrs/attrs/issues/321

**Comment by nicoddemus** [comment]
Alternatively you might pin `pytest` to `3.2` which does not require `attrs` (dependency to `attrs` was introduced in `3.3`), at least until the `attrs` issue with Jython is sorted out.

**Comment by hroncok** [comment]
That sounds like a good workaround for now.

**Comment by frenzymadness** [comment]
Thanks @nicoddemus! Workaround implemented in 1db9436067819b4e075f5e0b4d1fce08698c259c

**Comment by nicoddemus** [comment]
I suppose this can be closed now that 1db9436 is on `master`?

**Comment by frenzymadness** [comment]
Yes, sure. Closing…
